### ISSUE TITLE
Todo for next version

### ISSUE THREAD

**Issue by TheSeamau5** [TheSeamau5/elm-check#10]
- [ ] Push the updated version of elm-lazy-list
- [ ] Publish elm-rosetree
- [ ] Redefine elm-shrink in terms of lazy lists
- [ ] Modify the investigator type to generate shrink trees
- [ ] Add combinators like `map`, `flatMap`, etc... for investigators

**Comment by TheSeamau5** [comment]
Finally cracked how it would work! Yay!

```elm
import Random exposing (Generator)
import Lazy.List exposing (LazyList)
import Shrink exposing (Shrinker)

type RoseTree a = Rose a (LazyList (RoseTree a))

type alias Investigator a = Generator (RoseTree a)
  
shrinkTree : Shrinker a -> a -> RoseTree a 
shrinkTree shrink a = 
  let 
      list = 
        shrink a 
  in 
      Rose a (Lazy.List.map (shrinkTree shrink) list)


makeInvestigator : Generator a -> Shrinker a -> Investigator a
makeInvestigator gen shrink = 
  Random.map (shrinkTree shrink) gen
